import fs from 'node:fs/promises';
import path from 'node:path';
import { env } from '../env';
import { HttpError } from '../middleware/errorHandler';

// Attachment `key`s look like `tasks/<taskId>/<uuid>-<originalname>` and are
// always generated by us (see POST /:id/attachments), never taken verbatim
// from a client — resolving them under uploadsDir is still checked so a
// crafted key can't escape the uploads root.
function resolveKeyPath(key: string): string {
  const root = path.resolve(env.uploadsDir);
  const resolved = path.resolve(root, key);
  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    throw new HttpError(400, 'Invalid attachment path');
  }
  return resolved;
}

export async function uploadAttachment(key: string, body: Buffer): Promise<void> {
  const filePath = resolveKeyPath(key);
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, body);
}

export async function deleteAttachment(key: string): Promise<void> {
  const filePath = resolveKeyPath(key);
  await fs.unlink(filePath).catch((err: NodeJS.ErrnoException) => {
    if (err.code !== 'ENOENT') throw err;
  });
}

// Used by the download route to stream the file — the caller is responsible
// for checking the requester can view the task before calling this.
export function attachmentFilePath(key: string): string {
  return resolveKeyPath(key);
}
